env:
  global:
    - CC_TEST_REPORTER_ID=f6988edd-b63a-465c-9af1-95b126769bca
language: python
python:
 - "2.7"
install: pip install -r requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: sh run_travis.sh
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
